
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utuwhwpvaqsroafhedwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dXdod3B2YXFzcm9hZmhlZHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDIyNDAsImV4cCI6MjA2MDE3ODI0MH0.87UXZajn5ASgenXmrflp9GxJufgwbaHgiu5uuHNLNhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});
